server: https://192.168.56.92:9345
token: devsecops2025
tls-san:
  - 192.168.56.92
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
disable-apiserver: true
disable-controller-manager: true
disable-scheduler: true
node-ip: 192.168.56.71
cni: calico