server: https://192.168.56.92:9345
token: devsecops2025
tls-san:
  - 192.168.56.92
node-ip: 192.168.56.81
node-label: 
  - "dedicated=nodepool-env"
  - "node-role.kubernetes.io/worker=true"
# INSTALL_RKE2_TYPE="agent"
# INSTALL_RKE2_TYPE="server"
# INSTALL_RKE2_VERSION=v1.33.1+rke2r1