---
- name: Download install docker rancher script
  get_url:
    url: https://releases.rancher.com/install-docker/20.10.sh
    dest: /tmp/install-docker.20.10.sh
    mode: '0100'
- name: Install Docker
  shell: /tmp/install-docker.20.10.sh
- name: Start Docker service
  systemd_service:
    name: docker
    state: started
    enabled: true
- name: Grant Docker execution to ansible_user
  shell: sudo usermod -aG docker {{ ansible_user }}