nodes:
  - address: 192.168.56.60
    user: rkeoci
    role:
    - controlplane
    - etcd
    ssh_key_path: /home/rodrigo/projects/rancher-rke/keys/devsecops.pem
  - address: 192.168.56.70
    user: rkeoci
    role:
    - worker
    ssh_key_path: /home/rodrigo/projects/rancher-rke/keys/devsecops.pem
  - address: 192.168.56.80
    user: rkeoci
    role:
    - worker
    ssh_key_path: /home/rodrigo/projects/rancher-rke/keys/devsecops.pem

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"

kubernetes_version: v1.25.6-rancher4-1