nodes:
  - address: 192.168.56.90
    user: rkeoci
    role:
    - etcd
    ssh_key_path: /home/rodrigo/projects/rancher-rke/keys/devsecops.pem
  - address: 192.168.56.60
    user: rkeoci
    role:
    - controlplane
    ssh_key_path: /home/rodrigo/projects/rancher-rke/keys/devsecops.pem
  - address: 192.168.56.70
    user: rkeoci
    role:
    - worker
    ssh_key_path: /home/rodrigo/projects/rancher-rke/keys/devsecops.pem
  - address: 192.168.56.80
    user: rkeoci
    role:
    - worker
    ssh_key_path: /home/rodrigo/projects/rancher-rke/keys/devsecops.pem

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

network:
  plugin: flannel

# kubernetes_version: v1.30.10-rancher1-1
kubernetes_version: v1.31.6-rancher1-1